apiVersion: v1
data:
  secret: {{ .Values.secret | b64enc }}
  cert: {{ .Values.cert | quote }}
{{- $id :=  .Values.id }}
{{- $type := printf "%T" $id }}
  id: {{if eq $type "float64"}}{{ printf "%.0f" $id | b64enc }}{{ else }}{{ $id | b64enc }}{{ end }}
kind: Secret
metadata:
  name: {{ template "fullname" . }}
type: Opaque
